source 'https://rubygems.org'

gem 'rack', '< 2.0' # 2.0 requires Ruby 2.2+

# these are included to surface interactions between these gems and chef and
# compat_resource, particularly before 12.6.x when these gems will eagerly
# be loaded before compat_resource.
#
# FIXME: we should probably be using the versions that shipped with omnibus-chef
# at the time.  We should probably use TK to just install omnibus-chef.
gem 'chef-provisioning'
gem 'cheffish'

if ENV['GEMFILE_MOD']
  instance_eval(ENV['GEMFILE_MOD'])
else
  gem 'chef'
end
